### ISSUE TITLE
ValueError: gammavariate: alpha and beta must be > 0.0

### ISSUE THREAD

**Issue by 1988liszt** [aroth85/pyclone#1]
Hi, 

I am running pyclone and meet the follwing error. I don't know where the problem is. Could you help me? Thanks!
----------------------------------------------------------------------------------------------------
Here is my code:

[list@mu01 SB160306-1]$ PyClone run_analysis_pipeline --in_files XJX2_vs_XJX_1.tsv XJX3_vs_XJX_1.tsv --working_dir pyclone_analysis3 --prior total_copy_number
0 0 1.0
1000
Traceback (most recent call last):
  File "/data3/list/soft/miniconda2/bin/PyClone", line 337, in <module>
    main()
  File "/data3/list/soft/miniconda2/bin/PyClone", line 78, in main
    args.func(args)
  File "/data3/list/soft/miniconda2/lib/python2.7/site-packages/pyclone/run.py", line 38, in run_analysis_pipeline
    _run_analysis(config_file, args.seed)
  File "/data3/list/soft/miniconda2/lib/python2.7/site-packages/pyclone/run.py", line 173, in _run_analysis
    alpha_priors
  File "/data3/list/soft/miniconda2/lib/python2.7/site-packages/pyclone/pyclone_beta_binomial.py", line 68, in run_pyclone_beta_binomial_analysis
    sampler.sample(data.values(), trace, num_iters)
  File "/data3/list/soft/miniconda2/lib/python2.7/site-packages/pydp/samplers/dp.py", line 105, in sample
    self.interactive_sample(data)
  File "/data3/list/soft/miniconda2/lib/python2.7/site-packages/pydp/samplers/dp.py", line 115, in interactive_sample
    self.partition.number_of_items)
  File "/data3/list/soft/miniconda2/lib/python2.7/site-packages/pydp/samplers/concentration.py", line 56, in sample
    eta = beta_rvs(old_value + 1, n)
  File "/data3/list/soft/miniconda2/lib/python2.7/random.py", line 629, in betavariate
    return y / (y + self.gammavariate(beta, 1.))
  File "/data3/list/soft/miniconda2/lib/python2.7/random.py", line 508, in gammavariate
    raise ValueError, 'gammavariate: alpha and beta must be > 0.0'
ValueError: gammavariate: alpha and beta must be > 0.0

**Comment by choosehappy** [comment]
I have the same issue using a fresh install and the provided example files:

PyClone run_analysis_pipeline --in_files SRR385938.tsv SRR385939.tsv SRR385940.tsv SRR385941.tsv --working_dir pyclone_analysis


Did anyone else come across this? Find a fix?

**Comment by desnar** [comment]
You need pydp 0.2.4, https://github.com/aroth85/pydp/tree/0.2.4

**Comment by logan-leak** [comment]
How do you update the existing pydp to the newer version 0.2.4?

**Comment by qindan2008** [comment]
> You need pydp 0.2.4, https://github.com/aroth85/pydp/tree/0.2.4

I have tried this, but also failed.
