### ISSUE TITLE
ImportError: No module named cli

### ISSUE THREAD

**Issue by dawe** [aroth85/pyclone#16]
Hi, I have installed PyClone following instructions, through miniconda. Apparently it doesn't start as it cannot load properly subpackages:

```bash
$ PyClone 
Traceback (most recent call last):
  File "/home/dcittaro/miniconda3/envs/pyclone2/bin/PyClone", line 11, in <module>
    load_entry_point('PyClone==0.13.1', 'console_scripts', 'PyClone')()
  File "/home/dcittaro/miniconda3/envs/pyclone2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/dcittaro/miniconda3/envs/pyclone2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/dcittaro/miniconda3/envs/pyclone2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/dcittaro/miniconda3/envs/pyclone2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named cli
```

Has anybody experienced something similar?

**Comment by fangjialing** [comment]
no one

**Comment by xiasijian** [comment]
![image](https://user-images.githubusercontent.com/39158528/205607523-27c92d8e-66c2-43a9-8f19-4148081372ef.png)

The same error for me, how do you slove it?
